### ISSUE TITLE
Increase Retweet & Quote Retweet box sizes

### ISSUE THREAD

**Issue by Scowl821** [dimdenGD/OldTwitter#177]
![image](https://github.com/dimdenGD/OldTwitter/assets/76181880/14a2f4f3-23ec-470c-a914-3ce00e26058e)
Allow an Option to increase the size of these buttons. currently they are harder to click than on the vanilla version of twitter imo.

**Comment by dimdenGD** [comment]
This won't be added as specific setting but you can paste this to your Custom CSS field to make them bigger:
```css
.tweet-interact-retweet-menu span:before {
    font-size: 20px;
}
.tweet-interact-retweet-menu span {
    font-size: 18px;
    padding: 6px 18px;
}
```
