### ISSUE TITLE
It seems that the numbers for replies, retweets, and likes might be crowded together.

### ISSUE THREAD

**Issue by lrisora** [dimdenGD/OldTwitter#399]
![圖片](https://github.com/dimdenGD/OldTwitter/assets/43085437/4759904d-528d-4690-90d0-76151e505175)

Might need to add the following css or similar.
```css
.tweet-footer-stat-count {
  padding-right: 10px; /* Don't use this, it's not good for right-to-left languages */
}
```

It might also be possible to format it to a shorter form at the same time.

```js
Number(11111).toLocaleString(['zh-CN','en-US'],{ 
  notation: 'compact',
  compactDisplay: 'short',
  maximumFractionDigits: 1
});
```
