### ISSUE TITLE
grid view for media tab

### ISSUE THREAD

**Issue by THErlego** [dimdenGD/OldTwitter#635]
something that could be placed as a toggle in the ... menu on the tab selector on profiles, have images show in a grid similar to the new newtwitter update (its also canon because 2017 twitter mobile did not show any text on media tab)

**Comment by JimMcBubbles** [comment]
would also like somthing like this (or any way to veiw only images when searching)

**Comment by mmaker-gh** [comment]
I wrote some CSS that accomplishes this. Note your browser needs to support the [`:has()` selector](https://caniuse.com/css-has) (in order to only target when the media tab is active, or in photo/video searches). It's not perfect but works enough for my needs.

```css
:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
) {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    overflow: hidden;
    width: 590px;
    gap: 4px;
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet,
:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet * {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet {
    width: calc((590px / 3) - 4px);
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet > :not(.tweet-body),
:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet-body > :not(.tweet-media, .tweet-card),
:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet-media :is(.tweet-media-element:not(:first-of-type), video + img, img + video)
{
    display: none;
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
) 
:is(.tweet-media, iframe) {
    max-width: calc(590px / 3);
    aspect-ratio: 1 / 1;
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
:is(.tweet-media-element) {
    max-width: 100%;
    max-height: 100%;
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
:is(.tweet-media-element, iframe) {
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: center;
    border-radius: 0;
    /* pointer-events: none; */
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet-active::after {
    display: none;
}

:is(
    #tweet-nav:has(#tweet-nav-media.tweet-nav-active) ~ section #timeline,
    #left-cell:has(:is(#ns-photos, #ns-videos).search-switch-active) + div #timeline
)
.tweet:hover {
    padding: 8px 0;
    border-bottom: 2px solid var(--link-color);
}
```

<details><summary>Preview</summary>

![image](https://github.com/user-attachments/assets/da0fec2f-ea68-44c9-b7e0-2d7a81b8da7a)

</details>
